<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('production_expense_categories', function (Blueprint $table) { $table->id(); $table->string('code', 50)->unique(); $table->string('name', 120); $table->foreignId('expense_account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('part_boms', function (Blueprint $table) { $table->id(); $table->foreignId('part_id')->constrained('parts')->restrictOnDelete(); $table->string('version', 30); $table->decimal('output_quantity', 20, 6)->default(1); $table->enum('status', ['DRAFT','ACTIVE','INACTIVE'])->default('DRAFT'); $table->date('effective_from')->nullable(); $table->date('effective_to')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->unique(['part_id','version']); });
        Schema::create('part_bom_items', function (Blueprint $table) { $table->id(); $table->foreignId('part_bom_id')->constrained('part_boms')->cascadeOnDelete(); $table->foreignId('raw_material_id')->constrained('raw_materials')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('required_quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('wastage_percent', 8, 4)->default(0); $table->timestamps(); $table->unique(['part_bom_id','raw_material_id']); });
        Schema::create('part_production_batches', function (Blueprint $table) { $table->id(); $table->string('batch_no', 50)->unique(); $table->foreignId('part_bom_id')->constrained('part_boms')->restrictOnDelete(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('input_warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->foreignId('output_warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->date('production_date'); $table->decimal('planned_quantity', 20, 6); $table->decimal('good_quantity', 20, 6)->default(0); $table->decimal('reject_quantity', 20, 6)->default(0); $table->enum('qc_status', ['PENDING','PASSED','PARTIAL','FAILED'])->default('PENDING'); $table->enum('status', ['DRAFT','IN_PROGRESS','COMPLETED','VOID'])->default('DRAFT'); $table->text('qc_note')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('completed_at')->nullable(); $table->timestamps(); });
        Schema::create('part_production_consumptions', function (Blueprint $table) { $table->id(); $table->foreignId('part_production_batch_id')->constrained('part_production_batches')->cascadeOnDelete(); $table->foreignId('raw_material_id')->constrained('raw_materials')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('unit_cost', 20, 4)->default(0); $table->decimal('total_cost', 20, 4)->default(0); $table->timestamps(); });
        Schema::create('part_production_expenses', function (Blueprint $table) { $table->id(); $table->foreignId('part_production_batch_id')->constrained('part_production_batches')->cascadeOnDelete(); $table->foreignId('production_expense_category_id')->constrained('production_expense_categories')->restrictOnDelete(); $table->foreignId('account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->decimal('amount', 20, 4); $table->string('allocation_basis', 30)->default('BATCH'); $table->text('note')->nullable(); $table->timestamps(); });

        Schema::create('product_boms', function (Blueprint $table) { $table->id(); $table->foreignId('finished_product_id')->constrained('finished_products')->restrictOnDelete(); $table->string('version', 30); $table->decimal('output_quantity', 20, 6)->default(1); $table->enum('status', ['DRAFT','ACTIVE','INACTIVE'])->default('DRAFT'); $table->date('effective_from')->nullable(); $table->date('effective_to')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->unique(['finished_product_id','version']); });
        Schema::create('product_bom_items', function (Blueprint $table) { $table->id(); $table->foreignId('product_bom_id')->constrained('product_boms')->cascadeOnDelete(); $table->foreignId('raw_material_id')->nullable()->constrained('raw_materials')->restrictOnDelete(); $table->foreignId('part_id')->nullable()->constrained('parts')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('required_quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('wastage_percent', 8, 4)->default(0); $table->timestamps(); });
        Schema::create('product_assembly_batches', function (Blueprint $table) { $table->id(); $table->string('batch_no', 50)->unique(); $table->foreignId('product_bom_id')->constrained('product_boms')->restrictOnDelete(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('input_warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->foreignId('output_warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->date('assembly_date'); $table->decimal('planned_quantity', 20, 6); $table->decimal('good_quantity', 20, 6)->default(0); $table->decimal('reject_quantity', 20, 6)->default(0); $table->enum('qc_status', ['PENDING','PASSED','PARTIAL','FAILED'])->default('PENDING'); $table->enum('status', ['DRAFT','IN_PROGRESS','COMPLETED','VOID'])->default('DRAFT'); $table->text('qc_note')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('completed_at')->nullable(); $table->timestamps(); });
        Schema::create('product_assembly_consumptions', function (Blueprint $table) { $table->id(); $table->foreignId('product_assembly_batch_id')->constrained('product_assembly_batches')->cascadeOnDelete(); $table->foreignId('raw_material_id')->nullable()->constrained('raw_materials')->restrictOnDelete(); $table->foreignId('part_id')->nullable()->constrained('parts')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('unit_cost', 20, 4)->default(0); $table->decimal('total_cost', 20, 4)->default(0); $table->timestamps(); });
        Schema::create('product_assembly_expenses', function (Blueprint $table) { $table->id(); $table->foreignId('product_assembly_batch_id')->constrained('product_assembly_batches')->cascadeOnDelete(); $table->foreignId('production_expense_category_id')->constrained('production_expense_categories')->restrictOnDelete(); $table->foreignId('account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->decimal('amount', 20, 4); $table->string('allocation_basis', 30)->default('BATCH'); $table->text('note')->nullable(); $table->timestamps(); });

        if (DB::getDriverName() === 'mysql') foreach (['product_bom_items','product_assembly_consumptions'] as $table) DB::statement("ALTER TABLE `$table` ADD CONSTRAINT `{$table}_one_item_chk` CHECK ((`raw_material_id` IS NOT NULL) + (`part_id` IS NOT NULL) = 1)");
    }

    public function down(): void
    {
        foreach (['product_assembly_expenses','product_assembly_consumptions','product_assembly_batches','product_bom_items','product_boms','part_production_expenses','part_production_consumptions','part_production_batches','part_bom_items','part_boms','production_expense_categories'] as $table) Schema::dropIfExists($table);
    }
};
