<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) { $table->id(); $table->string('name', 100); $table->timestamps(); });
        Schema::create('divisions', function (Blueprint $table) { $table->id(); $table->string('name', 100); $table->string('bn_name', 100)->nullable(); $table->string('url', 100)->nullable(); $table->timestamps(); });
        Schema::create('districts', function (Blueprint $table) { $table->increments('district_id'); $table->unsignedBigInteger('district_division_id'); $table->string('district_name', 100); $table->string('district_bn_name', 100)->nullable(); $table->string('district_lat', 30)->nullable(); $table->string('district_lon', 30)->nullable(); $table->string('district_url', 100)->nullable(); $table->boolean('is_trash')->default(false); $table->timestamps(); $table->foreign('district_division_id')->references('id')->on('divisions')->restrictOnDelete(); });
        Schema::create('upazilas', function (Blueprint $table) { $table->id(); $table->unsignedInteger('upazila_district_id'); $table->string('upazila_name', 100); $table->string('upazila_bn_name', 100)->nullable(); $table->string('upazila_url', 100)->nullable(); $table->boolean('is_trash')->default(false); $table->timestamps(); $table->foreign('upazila_district_id')->references('district_id')->on('districts')->restrictOnDelete(); });

        Schema::create('units', function (Blueprint $table) { $table->id(); $table->string('name', 100); $table->string('code', 16)->unique(); $table->unsignedTinyInteger('precision')->default(0); $table->boolean('is_active')->default(true)->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('unit_conversions', function (Blueprint $table) { $table->id(); $table->foreignId('from_unit_id')->constrained('units')->restrictOnDelete(); $table->foreignId('to_unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('factor', 20, 6); $table->timestamps(); $table->unique(['from_unit_id', 'to_unit_id']); });
        Schema::create('brands', function (Blueprint $table) { $table->id(); $table->string('name', 150); $table->string('slug', 191)->unique(); $table->boolean('is_active')->default(true)->index(); $table->string('image')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->text('meta_keywords')->nullable(); $table->string('meta_image')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('suppliers', function (Blueprint $table) { $table->id(); $table->string('code', 50)->nullable()->unique(); $table->string('name', 150); $table->string('slug', 191)->nullable(); $table->string('phone', 32)->nullable()->unique(); $table->string('email', 191)->nullable()->unique(); $table->string('address')->nullable(); $table->string('postal_code', 20)->nullable(); $table->string('image')->nullable(); $table->boolean('is_active')->default(true); $table->timestamps(); $table->softDeletes(); });
        Schema::create('customers', function (Blueprint $table) { $table->id(); $table->string('code', 50)->nullable()->unique(); $table->string('name', 150); $table->string('slug', 191)->nullable(); $table->string('email', 191)->nullable()->unique(); $table->string('phone', 32)->nullable()->unique(); $table->string('alternate_phone', 32)->nullable(); $table->string('address')->nullable(); $table->string('postal_code', 20)->nullable(); $table->string('image')->nullable(); $table->boolean('is_active')->default(true); $table->date('birth_date')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('payment_types', function (Blueprint $table) { $table->id(); $table->string('name', 120); $table->string('slug', 120)->unique(); $table->string('image')->nullable(); $table->boolean('is_active')->default(true); $table->timestamps(); });

        Schema::create('account_types', function (Blueprint $table) { $table->id(); $table->string('name', 50); $table->string('code', 20)->nullable()->unique(); $table->enum('normal_balance', ['DEBIT', 'CREDIT'])->nullable(); $table->timestamps(); });
        Schema::create('accounts', function (Blueprint $table) { $table->id(); $table->foreignId('account_type_id')->constrained('account_types')->restrictOnDelete(); $table->foreignId('parent_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->string('name', 100); $table->string('code', 50)->nullable()->unique(); $table->string('description')->nullable(); $table->string('currency', 10)->default('BDT'); $table->string('bank_name', 100)->nullable(); $table->string('bank_account_no', 100)->nullable(); $table->text('bank_details')->nullable(); $table->boolean('allow_negative')->default(false); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('branch_accounts', function (Blueprint $table) { $table->id(); $table->foreignId('branch_id')->constrained('branches')->cascadeOnDelete(); $table->foreignId('account_id')->constrained('accounts')->cascadeOnDelete(); $table->boolean('is_active')->default(true); $table->boolean('is_default')->default(false); $table->timestamps(); $table->unique(['branch_id', 'account_id']); });
        Schema::create('fiscal_years', function (Blueprint $table) { $table->id(); $table->string('name', 50); $table->date('start_date'); $table->date('end_date'); $table->boolean('is_active')->default(false); $table->timestamps(); $table->unique(['start_date', 'end_date']); });
        Schema::create('voucher_types', function (Blueprint $table) { $table->id(); $table->string('name', 50); $table->string('code', 30)->unique(); $table->timestamps(); });
        Schema::create('number_sequences', function (Blueprint $table) { $table->id(); $table->string('key_name', 50); $table->foreignId('branch_id')->nullable()->constrained('branches')->cascadeOnDelete(); $table->foreignId('fiscal_year_id')->nullable()->constrained('fiscal_years')->cascadeOnDelete(); $table->unsignedBigInteger('current_number')->default(0); $table->timestamps(); $table->unique(['key_name', 'branch_id', 'fiscal_year_id'], 'number_sequences_scope_unique'); });
        Schema::create('journal_entries', function (Blueprint $table) { $table->id(); $table->string('voucher_no', 50); $table->foreignId('voucher_type_id')->constrained('voucher_types')->restrictOnDelete(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('fiscal_year_id')->constrained('fiscal_years')->restrictOnDelete(); $table->string('source_type', 80)->nullable(); $table->unsignedBigInteger('source_id')->nullable(); $table->date('entry_date'); $table->enum('status', ['DRAFT', 'POSTED', 'VOID'])->default('DRAFT'); $table->text('narration')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->foreignId('reversal_of_id')->nullable()->constrained('journal_entries')->restrictOnDelete(); $table->timestamps(); $table->unique(['branch_id', 'voucher_no']); $table->index(['source_type', 'source_id']); $table->index(['branch_id', 'entry_date', 'status']); });
        Schema::create('journal_entry_lines', function (Blueprint $table) { $table->id(); $table->foreignId('journal_entry_id')->constrained('journal_entries')->cascadeOnDelete(); $table->foreignId('account_id')->constrained('accounts')->restrictOnDelete(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->decimal('debit', 20, 4)->default(0); $table->decimal('credit', 20, 4)->default(0); $table->string('memo')->nullable(); $table->timestamps(); });
    }

    public function down(): void
    {
        foreach (['journal_entry_lines','journal_entries','number_sequences','voucher_types','fiscal_years','branch_accounts','accounts','account_types','payment_types','customers','suppliers','brands','unit_conversions','units','upazilas','districts','divisions','countries'] as $table) Schema::dropIfExists($table);
    }
};
