<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('expense_categories', function (Blueprint $table) { $table->id(); $table->string('code', 50)->unique(); $table->string('name', 120); $table->foreignId('expense_account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('expenses', function (Blueprint $table) { $table->id(); $table->string('expense_no', 50)->unique(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('expense_category_id')->constrained('expense_categories')->restrictOnDelete(); $table->date('expense_date'); $table->string('payee', 150)->nullable(); $table->decimal('amount', 20, 4); $table->enum('status', ['DRAFT','APPROVED','POSTED','VOID'])->default('DRAFT'); $table->text('description')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->timestamps(); $table->index(['branch_id','expense_date','status']); });
        Schema::create('expense_payments', function (Blueprint $table) { $table->id(); $table->foreignId('expense_id')->constrained('expenses')->cascadeOnDelete(); $table->foreignId('payment_type_id')->constrained('payment_types')->restrictOnDelete(); $table->foreignId('account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->decimal('amount', 20, 4); $table->string('reference_no', 100)->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); });

        Schema::create('sales', function (Blueprint $table) { $table->id(); $table->string('sale_no', 50)->unique(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->foreignId('customer_id')->nullable()->constrained('customers')->restrictOnDelete(); $table->enum('channel', ['POS','WHOLESALE']); $table->dateTime('sale_at'); $table->enum('status', ['DRAFT','POSTED','VOID'])->default('DRAFT'); $table->decimal('subtotal', 20, 4)->default(0); $table->decimal('discount', 20, 4)->default(0); $table->decimal('tax', 20, 4)->default(0); $table->decimal('total', 20, 4)->default(0); $table->decimal('paid_amount', 20, 4)->default(0); $table->decimal('due_amount', 20, 4)->default(0); $table->text('note')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('posted_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('posted_at')->nullable(); $table->timestamps(); $table->index(['branch_id','sale_at','status']); $table->index(['customer_id','sale_at']); });
        Schema::create('sale_items', function (Blueprint $table) { $table->id(); $table->foreignId('sale_id')->constrained('sales')->cascadeOnDelete(); $table->foreignId('finished_product_id')->constrained('finished_products')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('conversion_to_base', 20, 6)->default(1); $table->decimal('quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('unit_price', 20, 4); $table->decimal('discount', 20, 4)->default(0); $table->decimal('tax', 20, 4)->default(0); $table->decimal('line_total', 20, 4); $table->decimal('unit_cost', 20, 4)->nullable(); $table->timestamps(); });
        Schema::create('sale_payments', function (Blueprint $table) { $table->id(); $table->string('payment_no', 50)->unique(); $table->foreignId('sale_id')->constrained('sales')->cascadeOnDelete(); $table->foreignId('payment_type_id')->constrained('payment_types')->restrictOnDelete(); $table->foreignId('account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->dateTime('payment_at'); $table->decimal('amount', 20, 4); $table->string('reference_no', 100)->nullable(); $table->enum('status', ['DRAFT','POSTED','VOID'])->default('DRAFT'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); });
        Schema::create('sale_returns', function (Blueprint $table) { $table->id(); $table->string('return_no', 50)->unique(); $table->foreignId('sale_id')->constrained('sales')->restrictOnDelete(); $table->foreignId('branch_id')->constrained('branches')->restrictOnDelete(); $table->foreignId('warehouse_id')->constrained('warehouses')->restrictOnDelete(); $table->dateTime('return_at'); $table->enum('status', ['DRAFT','POSTED','VOID'])->default('DRAFT'); $table->decimal('total', 20, 4)->default(0); $table->text('reason')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('posted_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('posted_at')->nullable(); $table->timestamps(); });
        Schema::create('sale_return_items', function (Blueprint $table) { $table->id(); $table->foreignId('sale_return_id')->constrained('sale_returns')->cascadeOnDelete(); $table->foreignId('sale_item_id')->constrained('sale_items')->restrictOnDelete(); $table->foreignId('finished_product_id')->constrained('finished_products')->restrictOnDelete(); $table->foreignId('unit_id')->constrained('units')->restrictOnDelete(); $table->decimal('quantity', 20, 6); $table->decimal('base_quantity', 20, 6); $table->decimal('unit_price', 20, 4); $table->decimal('line_total', 20, 4); $table->timestamps(); });
        Schema::create('sale_return_payments', function (Blueprint $table) { $table->id(); $table->foreignId('sale_return_id')->constrained('sale_returns')->cascadeOnDelete(); $table->foreignId('payment_type_id')->constrained('payment_types')->restrictOnDelete(); $table->foreignId('account_id')->nullable()->constrained('accounts')->restrictOnDelete(); $table->decimal('amount', 20, 4); $table->string('reference_no', 100)->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); });
    }

    public function down(): void
    {
        foreach (['sale_return_payments','sale_return_items','sale_returns','sale_payments','sale_items','sales','expense_payments','expenses','expense_categories'] as $table) Schema::dropIfExists($table);
    }
};
